#!/bin/bash

#
# highest filename [howmany]
#
# Print howmany highest numbered lines in file filename.
# The input file is assumed to have lines taht start with
# numbers. Default fow howmany is 10.
#

if [ -z "$1" ]; then
  echo 'usage: higheest filanem [-N]'
  exit 1
fi

filename=$1
filename=${filename:?"missing."}
howmany=${2:-10}

header=$3

echo -e -n ${header:+"ALUMSARTIST\n"}
sort -nr $filename | head -$howmany 
